# Generated by Django 4.0.6 on 2022-10-25 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='作者')),
                ('age', models.IntegerField(verbose_name='年齡')),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='出版社名')),
                ('email', models.EmailField(max_length=254, verbose_name='出版社電郵')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('sex', models.BooleanField(default=1, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('class_null', models.CharField(max_length=5, verbose_name='班级编号')),
                ('description', models.TextField(max_length=1000, verbose_name='學生描述')),
            ],
            options={
                'db_table': 'tb_student',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='書名')),
                ('price', models.IntegerField(verbose_name='價格')),
                ('pub_date', models.DateField(verbose_name='出版日期')),
                ('bread', models.IntegerField(verbose_name='閱讀數')),
                ('bcomment', models.IntegerField(verbose_name='評論量')),
                ('publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.publish', verbose_name='出版社')),
            ],
        ),
    ]
